defaults:
  - infra: tryton
  - experiments/c_scale_inference@experiments.c_scale_inference
  - experiments/powell_initial_vector_set@experiments.powell_initial_vector_set
  - experiments/c_matrix_collection@experiments.c_matrix_collection
  - experiments/powell_c_matrix@experiments.powell_c_matrix
  - _self_
